apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: recipe-book-data
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  # storageClassName: local-path   # uncomment if using rancher local-path-provisioner
